import { ClientProviders } from 'apps/fe/modules/providers/ClientProviders';
import './global.css';

export const metadata = {
  title: 'Welcome to fe',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
