/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Template
 * Template API description
 * OpenAPI spec version: 1.0
 */
import {
  useInfiniteQuery,
  useMutation,
  useQuery,
  useSuspenseInfiniteQuery,
  useSuspenseQuery,
} from '@tanstack/react-query';
import type {
  InfiniteData,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseInfiniteQueryOptions,
  UseSuspenseInfiniteQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
  AccountDto,
  AccountsControllerFindAll200,
  AccountsControllerFindAllParams,
  CompaniesControllerFindAll200,
  CompaniesControllerFindAllParams,
  CreateAccountDto,
  UpdateAccountDto,
} from '../openapi-schemas';
import { customClient } from '../custom-client';
import type { ErrorType, BodyType } from '../custom-client';

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P
) => any
  ? P
  : never;

export const accountsControllerCreate = (
  createAccountDto: BodyType<CreateAccountDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<AccountDto>(
    {
      url: `/v1/accounts`,
      method: 'post',
      headers: { 'Content-Type': 'application/json' },
      data: createAccountDto,
    },
    options
  );
};

export const getAccountsControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountsControllerCreate>>,
    TError,
    { data: BodyType<CreateAccountDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountsControllerCreate>>,
  TError,
  { data: BodyType<CreateAccountDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountsControllerCreate>>,
    { data: BodyType<CreateAccountDto> }
  > = (props) => {
    const { data } = props ?? {};

    return accountsControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountsControllerCreate>>
>;
export type AccountsControllerCreateMutationBody = BodyType<CreateAccountDto>;
export type AccountsControllerCreateMutationError = ErrorType<void>;

export const useAccountsControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountsControllerCreate>>,
    TError,
    { data: BodyType<CreateAccountDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions = getAccountsControllerCreateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const accountsControllerFindAll = (
  params?: AccountsControllerFindAllParams,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<AccountsControllerFindAll200>(
    { url: `/v1/accounts`, method: 'get', params, signal },
    options
  );
};

export const getAccountsControllerFindAllQueryKey = (
  params?: AccountsControllerFindAllParams
) => {
  return [`/v1/accounts`, ...(params ? [params] : [])] as const;
};

export const getAccountsControllerFindAllInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof accountsControllerFindAll>>,
    AccountsControllerFindAllParams['cursor']
  >,
  TError = ErrorType<void>
>(
  params?: AccountsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindAll>>,
        TError,
        TData,
        Awaited<ReturnType<typeof accountsControllerFindAll>>,
        QueryKey,
        AccountsControllerFindAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAccountsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accountsControllerFindAll>>,
    QueryKey,
    AccountsControllerFindAllParams['cursor']
  > = ({ signal, pageParam }) =>
    accountsControllerFindAll(
      { cursor: pageParam, ...params },
      requestOptions,
      signal
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof accountsControllerFindAll>>,
    TError,
    TData,
    Awaited<ReturnType<typeof accountsControllerFindAll>>,
    QueryKey,
    AccountsControllerFindAllParams['cursor']
  > & { queryKey: QueryKey };
};

export type AccountsControllerFindAllInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountsControllerFindAll>>
>;
export type AccountsControllerFindAllInfiniteQueryError = ErrorType<void>;

export const useAccountsControllerFindAllInfinite = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof accountsControllerFindAll>>,
    AccountsControllerFindAllParams['cursor']
  >,
  TError = ErrorType<void>
>(
  params?: AccountsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindAll>>,
        TError,
        TData,
        Awaited<ReturnType<typeof accountsControllerFindAll>>,
        QueryKey,
        AccountsControllerFindAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAccountsControllerFindAllInfiniteQueryOptions(
    params,
    options
  );

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAccountsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof accountsControllerFindAll>>,
  TError = ErrorType<void>
>(
  params?: AccountsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAccountsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accountsControllerFindAll>>
  > = ({ signal }) => accountsControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof accountsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AccountsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountsControllerFindAll>>
>;
export type AccountsControllerFindAllQueryError = ErrorType<void>;

export const useAccountsControllerFindAll = <
  TData = Awaited<ReturnType<typeof accountsControllerFindAll>>,
  TError = ErrorType<void>
>(
  params?: AccountsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAccountsControllerFindAllQueryOptions(
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAccountsControllerFindAllSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof accountsControllerFindAll>>,
  TError = ErrorType<void>
>(
  params?: AccountsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAccountsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accountsControllerFindAll>>
  > = ({ signal }) => accountsControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof accountsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AccountsControllerFindAllSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountsControllerFindAll>>
>;
export type AccountsControllerFindAllSuspenseQueryError = ErrorType<void>;

export const useAccountsControllerFindAllSuspense = <
  TData = Awaited<ReturnType<typeof accountsControllerFindAll>>,
  TError = ErrorType<void>
>(
  params?: AccountsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAccountsControllerFindAllSuspenseQueryOptions(
    params,
    options
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAccountsControllerFindAllSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof accountsControllerFindAll>>,
    AccountsControllerFindAllParams['cursor']
  >,
  TError = ErrorType<void>
>(
  params?: AccountsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindAll>>,
        TError,
        TData,
        Awaited<ReturnType<typeof accountsControllerFindAll>>,
        QueryKey,
        AccountsControllerFindAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAccountsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accountsControllerFindAll>>,
    QueryKey,
    AccountsControllerFindAllParams['cursor']
  > = ({ signal, pageParam }) =>
    accountsControllerFindAll(
      { cursor: pageParam, ...params },
      requestOptions,
      signal
    );

  return {
    queryKey,
    queryFn,
    ...queryOptions,
  } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof accountsControllerFindAll>>,
    TError,
    TData,
    Awaited<ReturnType<typeof accountsControllerFindAll>>,
    QueryKey,
    AccountsControllerFindAllParams['cursor']
  > & { queryKey: QueryKey };
};

export type AccountsControllerFindAllSuspenseInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountsControllerFindAll>>
>;
export type AccountsControllerFindAllSuspenseInfiniteQueryError =
  ErrorType<void>;

export const useAccountsControllerFindAllSuspenseInfinite = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof accountsControllerFindAll>>,
    AccountsControllerFindAllParams['cursor']
  >,
  TError = ErrorType<void>
>(
  params?: AccountsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindAll>>,
        TError,
        TData,
        Awaited<ReturnType<typeof accountsControllerFindAll>>,
        QueryKey,
        AccountsControllerFindAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAccountsControllerFindAllSuspenseInfiniteQueryOptions(
    params,
    options
  );

  const query = useSuspenseInfiniteQuery(
    queryOptions
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const accountsControllerFindOne = (
  id: string,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<AccountDto>(
    { url: `/v1/accounts/${id}`, method: 'get', signal },
    options
  );
};

export const getAccountsControllerFindOneQueryKey = (id: string) => {
  return [`/v1/accounts/${id}`] as const;
};

export const getAccountsControllerFindOneInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof accountsControllerFindOne>>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAccountsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accountsControllerFindOne>>
  > = ({ signal }) => accountsControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof accountsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AccountsControllerFindOneInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountsControllerFindOne>>
>;
export type AccountsControllerFindOneInfiniteQueryError = ErrorType<void>;

export const useAccountsControllerFindOneInfinite = <
  TData = InfiniteData<Awaited<ReturnType<typeof accountsControllerFindOne>>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAccountsControllerFindOneInfiniteQueryOptions(
    id,
    options
  );

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAccountsControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof accountsControllerFindOne>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAccountsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accountsControllerFindOne>>
  > = ({ signal }) => accountsControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof accountsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AccountsControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountsControllerFindOne>>
>;
export type AccountsControllerFindOneQueryError = ErrorType<void>;

export const useAccountsControllerFindOne = <
  TData = Awaited<ReturnType<typeof accountsControllerFindOne>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAccountsControllerFindOneQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAccountsControllerFindOneSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof accountsControllerFindOne>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAccountsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accountsControllerFindOne>>
  > = ({ signal }) => accountsControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof accountsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AccountsControllerFindOneSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountsControllerFindOne>>
>;
export type AccountsControllerFindOneSuspenseQueryError = ErrorType<void>;

export const useAccountsControllerFindOneSuspense = <
  TData = Awaited<ReturnType<typeof accountsControllerFindOne>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAccountsControllerFindOneSuspenseQueryOptions(
    id,
    options
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getAccountsControllerFindOneSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<Awaited<ReturnType<typeof accountsControllerFindOne>>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAccountsControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof accountsControllerFindOne>>
  > = ({ signal }) => accountsControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof accountsControllerFindOne>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type AccountsControllerFindOneSuspenseInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof accountsControllerFindOne>>
>;
export type AccountsControllerFindOneSuspenseInfiniteQueryError =
  ErrorType<void>;

export const useAccountsControllerFindOneSuspenseInfinite = <
  TData = InfiniteData<Awaited<ReturnType<typeof accountsControllerFindOne>>>,
  TError = ErrorType<void>
>(
  id: string,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof accountsControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getAccountsControllerFindOneSuspenseInfiniteQueryOptions(
    id,
    options
  );

  const query = useSuspenseInfiniteQuery(
    queryOptions
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const accountsControllerUpdate = (
  id: string,
  updateAccountDto: BodyType<UpdateAccountDto>,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<AccountDto>(
    {
      url: `/v1/accounts/${id}`,
      method: 'patch',
      headers: { 'Content-Type': 'application/json' },
      data: updateAccountDto,
    },
    options
  );
};

export const getAccountsControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountsControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdateAccountDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountsControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateAccountDto> },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountsControllerUpdate>>,
    { id: string; data: BodyType<UpdateAccountDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return accountsControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountsControllerUpdate>>
>;
export type AccountsControllerUpdateMutationBody = BodyType<UpdateAccountDto>;
export type AccountsControllerUpdateMutationError = ErrorType<void>;

export const useAccountsControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountsControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdateAccountDto> },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions = getAccountsControllerUpdateMutationOptions(options);

  return useMutation(mutationOptions);
};

export const accountsControllerRemove = (
  id: string,
  options?: SecondParameter<typeof customClient>
) => {
  return customClient<void>(
    { url: `/v1/accounts/${id}`, method: 'delete' },
    options
  );
};

export const getAccountsControllerRemoveMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountsControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof accountsControllerRemove>>,
  TError,
  { id: string },
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof accountsControllerRemove>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return accountsControllerRemove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AccountsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof accountsControllerRemove>>
>;

export type AccountsControllerRemoveMutationError = ErrorType<unknown>;

export const useAccountsControllerRemove = <
  TError = ErrorType<unknown>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof accountsControllerRemove>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customClient>;
}) => {
  const mutationOptions = getAccountsControllerRemoveMutationOptions(options);

  return useMutation(mutationOptions);
};

export const companiesControllerFindAll = (
  params?: CompaniesControllerFindAllParams,
  options?: SecondParameter<typeof customClient>,
  signal?: AbortSignal
) => {
  return customClient<CompaniesControllerFindAll200>(
    { url: `/v1/companies`, method: 'get', params, signal },
    options
  );
};

export const getCompaniesControllerFindAllQueryKey = (
  params?: CompaniesControllerFindAllParams
) => {
  return [`/v1/companies`, ...(params ? [params] : [])] as const;
};

export const getCompaniesControllerFindAllInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof companiesControllerFindAll>>,
    CompaniesControllerFindAllParams['cursor']
  >,
  TError = ErrorType<void>
>(
  params?: CompaniesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companiesControllerFindAll>>,
        TError,
        TData,
        Awaited<ReturnType<typeof companiesControllerFindAll>>,
        QueryKey,
        CompaniesControllerFindAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompaniesControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companiesControllerFindAll>>,
    QueryKey,
    CompaniesControllerFindAllParams['cursor']
  > = ({ signal, pageParam }) =>
    companiesControllerFindAll(
      { cursor: pageParam, ...params },
      requestOptions,
      signal
    );

  return { queryKey, queryFn, ...queryOptions } as UseInfiniteQueryOptions<
    Awaited<ReturnType<typeof companiesControllerFindAll>>,
    TError,
    TData,
    Awaited<ReturnType<typeof companiesControllerFindAll>>,
    QueryKey,
    CompaniesControllerFindAllParams['cursor']
  > & { queryKey: QueryKey };
};

export type CompaniesControllerFindAllInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof companiesControllerFindAll>>
>;
export type CompaniesControllerFindAllInfiniteQueryError = ErrorType<void>;

export const useCompaniesControllerFindAllInfinite = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof companiesControllerFindAll>>,
    CompaniesControllerFindAllParams['cursor']
  >,
  TError = ErrorType<void>
>(
  params?: CompaniesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companiesControllerFindAll>>,
        TError,
        TData,
        Awaited<ReturnType<typeof companiesControllerFindAll>>,
        QueryKey,
        CompaniesControllerFindAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCompaniesControllerFindAllInfiniteQueryOptions(
    params,
    options
  );

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getCompaniesControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof companiesControllerFindAll>>,
  TError = ErrorType<void>
>(
  params?: CompaniesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companiesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompaniesControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companiesControllerFindAll>>
  > = ({ signal }) =>
    companiesControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof companiesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CompaniesControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof companiesControllerFindAll>>
>;
export type CompaniesControllerFindAllQueryError = ErrorType<void>;

export const useCompaniesControllerFindAll = <
  TData = Awaited<ReturnType<typeof companiesControllerFindAll>>,
  TError = ErrorType<void>
>(
  params?: CompaniesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof companiesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCompaniesControllerFindAllQueryOptions(
    params,
    options
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getCompaniesControllerFindAllSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof companiesControllerFindAll>>,
  TError = ErrorType<void>
>(
  params?: CompaniesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companiesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompaniesControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companiesControllerFindAll>>
  > = ({ signal }) =>
    companiesControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof companiesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type CompaniesControllerFindAllSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof companiesControllerFindAll>>
>;
export type CompaniesControllerFindAllSuspenseQueryError = ErrorType<void>;

export const useCompaniesControllerFindAllSuspense = <
  TData = Awaited<ReturnType<typeof companiesControllerFindAll>>,
  TError = ErrorType<void>
>(
  params?: CompaniesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof companiesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = getCompaniesControllerFindAllSuspenseQueryOptions(
    params,
    options
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const getCompaniesControllerFindAllSuspenseInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof companiesControllerFindAll>>,
    CompaniesControllerFindAllParams['cursor']
  >,
  TError = ErrorType<void>
>(
  params?: CompaniesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companiesControllerFindAll>>,
        TError,
        TData,
        Awaited<ReturnType<typeof companiesControllerFindAll>>,
        QueryKey,
        CompaniesControllerFindAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getCompaniesControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof companiesControllerFindAll>>,
    QueryKey,
    CompaniesControllerFindAllParams['cursor']
  > = ({ signal, pageParam }) =>
    companiesControllerFindAll(
      { cursor: pageParam, ...params },
      requestOptions,
      signal
    );

  return {
    queryKey,
    queryFn,
    ...queryOptions,
  } as UseSuspenseInfiniteQueryOptions<
    Awaited<ReturnType<typeof companiesControllerFindAll>>,
    TError,
    TData,
    Awaited<ReturnType<typeof companiesControllerFindAll>>,
    QueryKey,
    CompaniesControllerFindAllParams['cursor']
  > & { queryKey: QueryKey };
};

export type CompaniesControllerFindAllSuspenseInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<typeof companiesControllerFindAll>>
>;
export type CompaniesControllerFindAllSuspenseInfiniteQueryError =
  ErrorType<void>;

export const useCompaniesControllerFindAllSuspenseInfinite = <
  TData = InfiniteData<
    Awaited<ReturnType<typeof companiesControllerFindAll>>,
    CompaniesControllerFindAllParams['cursor']
  >,
  TError = ErrorType<void>
>(
  params?: CompaniesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseSuspenseInfiniteQueryOptions<
        Awaited<ReturnType<typeof companiesControllerFindAll>>,
        TError,
        TData,
        Awaited<ReturnType<typeof companiesControllerFindAll>>,
        QueryKey,
        CompaniesControllerFindAllParams['cursor']
      >
    >;
    request?: SecondParameter<typeof customClient>;
  }
): UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions =
    getCompaniesControllerFindAllSuspenseInfiniteQueryOptions(params, options);

  const query = useSuspenseInfiniteQuery(
    queryOptions
  ) as UseSuspenseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};
