/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Template
 * Template API description
 * OpenAPI spec version: 1.0
 */

export type AccountsControllerFindAllParams = {
  page: number;
  pageSize: number;
};
