/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Template
 * Template API description
 * OpenAPI spec version: 1.0
 */
import type { PagedResponse } from './pagedResponse';
import type { AccountsControllerFindAll200AllOf } from './accountsControllerFindAll200AllOf';

export type AccountsControllerFindAll200 = PagedResponse &
  AccountsControllerFindAll200AllOf;
