/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * Template
 * Template API description
 * OpenAPI spec version: 1.0
 */
import type { CursorResponse } from './cursorResponse';
import type { CompaniesControllerFindAll200AllOf } from './companiesControllerFindAll200AllOf';

export type CompaniesControllerFindAll200 = CursorResponse &
  CompaniesControllerFindAll200AllOf;
