version: '3.9'
name: tanstack-demo
services:
  database:
    container_name: tanstack-demo.dev.database
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
